### ISSUE TITLE
batch_key name adata.obs['batch'] is hardcoded

### ISSUE THREAD

**Issue by maarten-hifibio** [suinleelab/contrastiveVI#1]
First of all, thank you for the great tool!
A small suggestion: currently, the `get_library_log_means_and_var()` function in `utils.py` requires that `adata.obs` has a column `batch`. It would be neat if this could be any column name, specifically the one specified by `batch_key` in `ContrastiveVIModel.setup_anndata()`.

**Comment by ethanweinberger** [comment]
Thanks for the feedback - glad to hear you're enjoying using contrastiveVI! I've put your request on my to-do list and should have it taken care of by the end of this week.

**Comment by ethanweinberger** [comment]
I just committed a change that modifies `get_library_log_means_and_var()` to automatically use the `batch_key` from `setup_anndata`. I'm going to close this issue for now, but let me know if you run into any more issues!
