### ISSUE TITLE
Alzheimer's Tutorial

### ISSUE THREAD

**Issue by JBreunig** [suinleelab/contrastiveVI#18]
I'm very interested to employ your elegant approach and started wth the tutorial.  Everything works except for these lines:

```
top_genes_per_cell_type[cell_type] = results_tmp.index[:num_top_genes]
    de_results[cell_type] = set(results_tmp.index)
```
I get these types of errors: 

> NameError: name 'top_genes_per_cell_type' is not defined

Any suggestions?

**Comment by ethanweinberger** [comment]
Hey @JBreunig,

I just took a quick look at the notebook, and it looks like that variable `top_genes_per_cell_type` isn't actually used anywhere so you should be able to remove it/comment it out. Let me know if that fixes the issue.
