### ISSUE TITLE
New scvi-tools breaking changes

### ISSUE THREAD

**Issue by adamgayoso** [suinleelab/contrastiveVI#2]
Hi contrastiveVI team!

I just wanted to let you know that we are soon going to release a version of scvi-tools that breaks your code. The fortunate thing is that it doesn't look hard to fix. You can read more here:

https://docs.scvi-tools.org/en/0.15.0-beta.0/release_notes/v0.15.0.html

Please feel free to reach out with any questions on our [discourse](https://discourse.scvi-tools.org/). As a first step you may consider upper bounding the version to <0.15.0, and then making the changes.

**Comment by ethanweinberger** [comment]
Hi @adamgayoso ,

Thanks for the heads up! We'll take a look and let you know if we run into any issues.

**Comment by chris522229197** [comment]
Addressed in https://github.com/suinleelab/contrastiveVI/pull/6.
